defaultNamespace: "emotes"
defaultFolder: "emotes"
defaultFont: "emotes"
defaultHeight: 7
defaultAscent: 7
requirePermission: true
generateResourcePack: true

emotes:
  - id: "emotes"
    texture: "emotes:emotes/pog.png"
    font: "emotes"
    height: 7
    ascent: 7
